services:
  web:
    build: .
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_TABLE=${SUPABASE_TABLE}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5000:5000"
    restart: unless-stopped
