services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    env_file:
      - .env
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - default
    links:
      - web